baseURL = 'https://sacrorum.com/'
languageCode = 'en-us'
title = 'Bogdan Novosad blog'
theme = 'ananke'
copyright = "Copyright 2023 Bogdan Novosad"
defaultContentLanguage = "en"
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "G-K4ZYFFEK0Q"